// scripts/seed/generate.mjs
// Deterministic SYNTHETIC data generator for the Savora Foods FMCG demo.
// Emits scripts/seed/savora_seed.sql (INSERTs matching 0001_init.sql exactly).
// Data is fabricated but statistically realistic so downstream z-scores/forecasts
// are meaningful. It encodes the dipdip narrative: Gopal price-war dip on SC-001
// (West, ~2026-05-11), a viral SC-003 Delhi NCR spike, and South/Karnataka growth.
//
// Run:  node scripts/seed/generate.mjs   ->   writes scripts/seed/savora_seed.sql

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))

// deterministic PRNG (mulberry32)
function rng(seed) {
  let a = seed >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
const rand = rng(20260601)
const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const day = (d) => d.toISOString().slice(0, 10)

// ---- SKUs (matches the Savora narrative) ----
const SKUS = [
  ['SC-001', 'Bhujia Premium 200g', 'snacks', 95, 58, ['West', 'North']],
  ['SC-002', 'Aloo Bhujia 200g', 'snacks', 85, 52, ['West', 'North']],
  ['SC-003', 'Masala Munch Mix 150g', 'snacks', 60, 34, ['Delhi NCR', 'North']],
  ['SC-004', 'Khatta Meetha 200g', 'snacks', 90, 55, ['West', 'South']],
  ['SM-001', 'Savora Garam Masala 100g', 'spices', 140, 78, ['West', 'South']],
  ['SM-002', 'Chaat Masala 100g', 'spices', 75, 40, ['North', 'Delhi NCR']],
  ['SM-003', 'Savora Masala South Blend 100g', 'spices', 120, 64, ['South', 'West']],
  ['SM-004', 'Turmeric Powder 200g', 'spices', 95, 52, ['South', 'North']],
  ['SR-001', 'Poha Mix 250g', 'ready_to_eat', 72, 41, ['West', 'Delhi NCR']],
  ['SR-002', 'Upma Mix 250g', 'ready_to_eat', 70, 40, ['South', 'West']],
  ['SR-003', 'Khichdi Ready 300g', 'ready_to_eat', 110, 63, ['North', 'West']],
  ['SR-004', 'Poha Mix Bundle 2x250g', 'ready_to_eat', 130, 74, ['West', 'Delhi NCR']],
]
const CHANNEL = { snacks: 'modern_trade', spices: 'general_trade', ready_to_eat: 'd2c' }

// ---- weekly timeline: 78 weeks ending 2026-05-25 ----
const WEEKS = []
{
  const end = new Date('2026-05-25T00:00:00Z')
  for (let i = 77; i >= 0; i--) WEEKS.push(new Date(end.getTime() - i * 7 * 86400000))
}

const lines = []
lines.push('-- savora_seed.sql — SYNTHETIC demo data (generated by scripts/seed/generate.mjs)')
lines.push('-- Do not present as live. Numbers are fabricated but internally consistent.')
lines.push('begin;')
lines.push('truncate sales, inventory, competitor_signal restart identity cascade;')
lines.push('delete from sku;')

// sku rows
for (const [id, name, cat, mrp, cost] of SKUS) {
  lines.push(
    `insert into sku (sku_id,name,category,mrp,unit_cost,launched_on) values (${q(id)},${q(name)},${q(cat)},${mrp},${cost},'2023-06-01') on conflict (sku_id) do nothing;`,
  )
}

// sales rows (weekly, per sku x home-region)
const seasonal = (d) => 1 + 0.18 * Math.sin((d.getUTCMonth() / 12) * 2 * Math.PI) // mild yearly cycle
for (const [id, , cat, mrp] of SKUS) {
  const skuMeta = SKUS.find((s) => s[0] === id)
  for (const region of skuMeta[5]) {
    const base = 400 + Math.floor(rand() * 600)
    const channel = CHANNEL[cat]
    WEEKS.forEach((d, wi) => {
      let mult = seasonal(d) * (0.85 + rand() * 0.3)
      // gentle growth, stronger in South (Karnataka expansion story)
      mult *= 1 + (wi / WEEKS.length) * (region === 'South' ? 0.35 : 0.12)
      // event: Gopal price war hits SC-001 West velocity around 2026-05-11
      if (id === 'SC-001' && region === 'West' && d >= new Date('2026-05-04') )
        mult *= 0.82
      // event: viral SC-003 spike in Delhi NCR mid-May 2026
      if (id === 'SC-003' && region === 'Delhi NCR' && d >= new Date('2026-05-11'))
        mult *= 1.41
      const units = Math.max(20, Math.round(base * mult))
      const price = mrp * (0.9 + rand() * 0.06) // realised price below MRP
      const revenue = Math.round(units * price)
      lines.push(
        `insert into sales (sku_id,region,channel,sale_date,units,revenue) values (${q(id)},${q(region)},${q(channel)},${q(day(d))},${units},${revenue});`,
      )
    })
  }
}

// inventory monthly snapshots (last 18 months) per sku x home-region
const MONTHS = []
{
  const end = new Date('2026-05-01T00:00:00Z')
  for (let i = 17; i >= 0; i--) MONTHS.push(new Date(end.getUTCFullYear(), end.getUTCMonth() - i, 1))
}
for (const [id, , , , ] of SKUS) {
  const skuMeta = SKUS.find((s) => s[0] === id)
  for (const region of skuMeta[5]) {
    const reorder = 300 + Math.floor(rand() * 200)
    MONTHS.forEach((m) => {
      let onHand = Math.round(reorder * (0.8 + rand() * 1.4))
      // SC-001 West runs low at the end (the price-war squeeze)
      if (id === 'SC-001' && region === 'West' && m >= new Date(2026, 3, 1))
        onHand = Math.round(reorder * 0.7)
      lines.push(
        `insert into inventory (sku_id,region,snapshot_date,on_hand,reorder_point) values (${q(id)},${q(region)},${q(day(m))},${onHand},${reorder});`,
      )
    })
  }
}

// competitor signals (from the narrative)
const SIGNALS = [
  ['Distributor tracker', 'Competitor', 'Gopal Snacks launched 20% flash sale on Bhujia variants in Gujarat & Rajasthan; SC-001 modern-trade reorder velocity down ~18% in 72h.', 'high', '2026-05-11', true],
  ['Demand model', 'Demand', 'SC-003 Masala Munch demand spiked ~41% above forecast in Delhi NCR; possible viral reel (67K shares).', 'high', '2026-05-13', true],
  ['Market intel', 'Competitor', 'Catch Spices signed a Mysore distributor last week, strengthening South Tier-2 coverage.', 'medium', '2026-05-06', false],
  ['Regulatory', 'Regulatory', 'Maharashtra eco-packaging regulation effective Q3 — 90-day compliance window for RTE packs.', 'medium', '2026-04-28', false],
  ['Supply', 'Supply', 'Turmeric raw-material prices up 9% MoM; SM-004 margin under mild pressure.', 'low', '2026-05-02', false],
  ['Demand model', 'Demand', 'Pune/Karnataka branded-spice demand up ~18% YoY; first-mover window for SM-003 distributors.', 'medium', '2026-05-09', false],
]
for (const [src, cat, body, impact, date, urg] of SIGNALS) {
  lines.push(
    `insert into competitor_signal (source,category,body,impact,detected_at,urgent) values (${q(src)},${q(cat)},${q(body)},${q(impact)},${q(date + 'T09:00:00Z')},${urg});`,
  )
}

lines.push('commit;')

const out = join(HERE, 'savora_seed.sql')
writeFileSync(out, lines.join('\n') + '\n')
console.log(`Wrote ${out} (${lines.length} statements).`)
